BEGIN;

CREATE TABLE IF NOT EXISTS public.uf_analysis (
	message_uuid character varying NOT NULL,
	start_time timestamp with time zone,
	submit_time timestamp with time zone,
	analyst_email character varying,
	is_useless boolean,
	resp_01 text,
	resp_02 text,
	resp_03 text,
	resp_04 text,
	resp_05 text,
	resp_06 text,
	resp_07 text,
	resp_08 text,
	resp_09 text,
	resp_10 text,
	resp_11 text,
	resp_12 text,
	resp_13 text,
	resp_14 text,
	resp_15 text,
	resp_16 text,
	resp_17 text,
	resp_18 text,
	resp_19 text,
	resp_20 text,
	resp_21 text,
	resp_22 text,
	resp_23 text,
	resp_24 text,
	resp_25 text,
	resp_26 text,
	resp_27 text,
	resp_28 text,
	resp_29 text,
	resp_30 text,
	resp_01_o text,
	resp_02_o text,
	resp_03_o text,
	resp_04_o text,
	resp_05_o text,
	resp_06_o text,
	resp_07_o text,
	resp_08_o text,
	resp_09_o text,
	resp_10_o text,
	resp_11_o text,
	resp_12_o text,
	resp_13_o text,
	resp_14_o text,
	resp_15_o text,
	resp_16_o text,
	resp_17_o text,
	resp_18_o text,
	resp_19_o text,
	resp_20_o text,
	resp_21_o text,
	resp_22_o text,
	resp_23_o text,
	resp_24_o text,
	resp_25_o text,
	resp_26_o text,
	resp_27_o text,
	resp_28_o text,
	resp_29_o text,
	resp_30_o text,
	PRIMARY KEY(message_uuid)
);

COMMIT;